export const USER = "USER";
export const PROJECTS = "PROJECTS";
export const SAFETY_SCOPE_MAIN_MODULE = "SAFETY_SCOPE_MAIN_MODULE";
export const LIVEBLOCKS_DATA = "LIVEBLOCKS_DATA";
export const CODE_EDITOR = "CODE_EDITOR";
export const GLOBAL_TAGS = [
  USER,
  PROJECTS,
  SAFETY_SCOPE_MAIN_MODULE,
  LIVEBLOCKS_DATA,
  CODE_EDITOR,
];
